# Generated by Django 5.0.2 on 2024-03-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtended',
        ),
    ]
